# Generated by Django 5.2.17 on 2026-08-15 23:52

import django.db.models.deletion
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_alter_registration_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=payments.models.generate_payment_reference, editable=False, max_length=32, unique=True)),
                ('paynow_reference', models.CharField(blank=True, max_length=64)),
                ('poll_url', models.URLField(blank=True, max_length=500)),
                ('browser_url', models.URLField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('method', models.CharField(choices=[('web', 'Paynow (card, Zimswitch or wallet)'), ('ecocash', 'EcoCash'), ('onemoney', 'OneMoney'), ('innbucks', 'InnBucks')], default='web', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('created', 'Created'), ('sent', 'Sent to Paynow'), ('paid', 'Paid'), ('awaiting_delivery', 'Paid — awaiting delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('expired', 'Expired')], default='created', max_length=30)),
                ('instructions', models.TextField(blank=True)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('is_simulated', models.BooleanField(default=False, help_text='Created without live Paynow credentials.')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='events.registration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference'], name='payments_pa_referen_75358f_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx')],
            },
        ),
    ]
