# Generated by Django 5.2.17 on 2026-08-16 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='confirmation_code',
            field=models.CharField(blank=True, help_text='EcoCash transaction code supplied by the payer', max_length=40),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_from',
            field=models.CharField(blank=True, help_text='Mobile number the transfer came from', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('ecocash_direct', 'EcoCash — send straight to us'), ('web', 'Paynow (card, Zimswitch or wallet)'), ('ecocash', 'EcoCash via Paynow'), ('onemoney', 'OneMoney'), ('innbucks', 'InnBucks')], default='web', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('sent', 'Sent to Paynow'), ('awaiting_transfer', 'Waiting for the EcoCash transfer'), ('awaiting_verification', 'Code submitted — awaiting check'), ('paid', 'Paid'), ('awaiting_delivery', 'Paid — awaiting delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('expired', 'Expired')], default='created', max_length=30),
        ),
    ]
