# Generated by Django 5.2.17 on 2026-08-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_confirmation_code_payment_paid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('pesepay', 'Pesepay'), ('paynow', 'Paynow'), ('direct', 'Direct transfer')], default='pesepay', help_text='Which processor handled this payment.', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('ecocash_direct', 'EcoCash — send straight to us'), ('web', 'Card, Zimswitch or any wallet'), ('ecocash', 'EcoCash'), ('onemoney', 'OneMoney'), ('innbucks', 'InnBucks')], default='web', max_length=20),
        ),
    ]
