# Generated by Django 5.2.17 on 2026-08-21 16:11

import django.db.models.deletion
import payments.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationclaim'),
        ('payments', '0003_payment_gateway_alter_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Assessed once, when the money settles. Historic rows keep the old rate.', max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=payments.models.generate_payout_reference, editable=False, max_length=32, unique=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='What actually leaves our account.', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Prepared, not yet sent'), ('paid', 'Sent'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('method', models.CharField(choices=[('ecocash', 'EcoCash'), ('bank', 'Bank transfer'), ('cash', 'Cash'), ('other', 'Other')], default='ecocash', max_length=20)),
                ('destination', models.CharField(blank=True, help_text='Wallet number or account the money went to.', max_length=120)),
                ('external_reference', models.CharField(blank=True, help_text='The EcoCash or bank confirmation code, so this can be reconciled.', max_length=80)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payout',
            field=models.ForeignKey(blank=True, help_text='The settlement to the society that covered this sale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.payout'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status'], name='payments_pa_status_d49350_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['reference'], name='payments_pa_referen_7d45c5_idx'),
        ),
    ]
