# Generated by Django 5.2.17 on 2026-08-19 14:49

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations

from varsity.dbops import AddIndexIfPostgres


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_search_vector'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Skipped on SQLite, which has no GIN. The index stays in model state
        # either way, so makemigrations doesn't ask for it again.
        AddIndexIfPostgres(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='event_search_vector_gin'),
        ),
    ]
