# Generated by Django 5.2.17 on 2026-08-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_search_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='reminded_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
