# Generated by Django 5.2.17 on 2026-08-21 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0006_event_review_note_event_reviewed_at_and_more'),
        ('organizations', '0002_organizationclaim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('scam', "It's a scam, or the tickets aren't real"), ('wrong', 'The details are wrong or misleading'), ('not_happening', "It's been cancelled, or it already happened"), ('impersonation', "It's pretending to be someone else"), ('offensive', "It's offensive or unsafe"), ('spam', "It's spam, or it isn't a real event"), ('other', 'Something else')], max_length=20)),
                ('detail', models.TextField(blank=True, help_text='Anything that would help us check it — what you saw, and where.', max_length=800)),
                ('status', models.CharField(choices=[('open', 'Open'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=300)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='events.event')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='organizations.organization')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_report_status_9a134a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('event__isnull', False), ('organization__isnull', True)), models.Q(('event__isnull', True), ('organization__isnull', False)), _connector='OR'), name='report_targets_exactly_one_thing'), models.UniqueConstraint(condition=models.Q(('event__isnull', False), ('status', 'open')), fields=('reporter', 'event'), name='one_open_report_per_person_per_event'), models.UniqueConstraint(condition=models.Q(('organization__isnull', False), ('status', 'open')), fields=('reporter', 'organization'), name='one_open_report_per_person_per_society')],
            },
        ),
    ]
