# Generated by Django 5.2.17 on 2026-08-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified_organizer',
            field=models.BooleanField(default=False, help_text='Staff have confirmed this person really runs what they say they run. Their events skip the review queue even from an unverified society.'),
        ),
    ]
