# Generated by Django 5.2.17 on 2026-08-16 00:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_alter_registration_status'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('registered', 'registered for'), ('paid', 'paid for'), ('waitlisted', 'joined the waitlist for'), ('checked_in', 'checked in at'), ('published', 'published'), ('sold_out', 'sold out'), ('followed', 'followed'), ('joined', 'joined'), ('reviewed', 'reviewed'), ('saved', 'saved')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_simulated', models.BooleanField(default=False, help_text='Generated by the activity simulator rather than a real person.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='events.event')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-pk'],
                'indexes': [models.Index(fields=['-id'], name='activity_ac_id_06460c_idx'), models.Index(fields=['verb', '-created_at'], name='activity_ac_verb_1fca4d_idx')],
            },
        ),
    ]
