# Generated by Django 5.2.17 on 2026-08-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='verb',
            field=models.CharField(choices=[('registered', 'registered for'), ('paid', 'paid for'), ('waitlisted', 'joined the waitlist for'), ('checked_in', 'checked in at'), ('published', 'published'), ('sold_out', 'sold out'), ('followed', 'followed'), ('joined', 'joined'), ('reviewed', 'reviewed'), ('saved', 'saved'), ('signed_up', 'joined Varsity Events')], max_length=20),
        ),
    ]
