"""A single append-only stream of everything happening on the platform.

Every meaningful domain action writes one row here. The live board and the
in-page tickers then read forward from the last id they saw, which keeps the
polling cheap — no timestamps to reconcile, no duplicates, no gaps.
"""

from django.conf import settings
from django.db import models
from django.utils import timezone


class ActivityQuerySet(models.QuerySet):
    def public(self):
        return self.filter(is_public=True)

    def since(self, last_id):
        return self.filter(pk__gt=last_id) if last_id else self

    def for_feed(self):
        return self.select_related(
            "actor", "actor__university", "event", "event__organization", "organization"
        ).order_by("-pk")


class Activity(models.Model):
    class Verb(models.TextChoices):
        REGISTERED = "registered", "registered for"
        PAID = "paid", "paid for"
        WAITLISTED = "waitlisted", "joined the waitlist for"
        CHECKED_IN = "checked_in", "checked in at"
        PUBLISHED = "published", "published"
        SOLD_OUT = "sold_out", "sold out"
        FOLLOWED = "followed", "followed"
        JOINED = "joined", "joined"
        REVIEWED = "reviewed", "reviewed"
        SAVED = "saved", "saved"
        SIGNED_UP = "signed_up", "joined Varsity Events"

    # Emoji + tone drive the ticker styling without a lookup table in the template.
    STYLES = {
        Verb.REGISTERED: ("🎟️", "brand"),
        Verb.PAID: ("💰", "emerald"),
        Verb.WAITLISTED: ("⏳", "amber"),
        Verb.CHECKED_IN: ("✅", "emerald"),
        Verb.PUBLISHED: ("📣", "violet"),
        Verb.SOLD_OUT: ("🔥", "rose"),
        Verb.FOLLOWED: ("⭐", "sky"),
        Verb.JOINED: ("🤝", "teal"),
        Verb.REVIEWED: ("⭐", "amber"),
        Verb.SAVED: ("🔖", "slate"),
        Verb.SIGNED_UP: ("👋", "brand"),
    }

    verb = models.CharField(max_length=20, choices=Verb.choices)
    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="activities",
    )
    event = models.ForeignKey(
        "events.Event", on_delete=models.CASCADE, null=True, blank=True, related_name="activities"
    )
    organization = models.ForeignKey(
        "organizations.Organization",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="activities",
    )
    amount = models.DecimalField(max_digits=9, decimal_places=2, null=True, blank=True)
    rating = models.PositiveSmallIntegerField(null=True, blank=True)

    is_public = models.BooleanField(default=True)
    is_simulated = models.BooleanField(
        default=False, help_text="Generated by the activity simulator rather than a real person."
    )
    created_at = models.DateTimeField(default=timezone.now, db_index=True)

    objects = ActivityQuerySet.as_manager()

    class Meta:
        verbose_name_plural = "activities"
        ordering = ["-pk"]
        indexes = [
            # The feed reads strictly backwards from the last id the client saw.
            models.Index(fields=["-id"]),
            models.Index(fields=["verb", "-created_at"]),
        ]

    def __str__(self):
        return f"{self.actor_name} {self.get_verb_display()} {self.target_name}"

    # -- presentation ---------------------------------------------------

    @property
    def actor_name(self):
        """First name plus a last initial — enough to feel real, not a directory listing."""
        if not self.actor:
            return "Someone"
        first = self.actor.first_name or self.actor.username
        last = self.actor.last_name
        return f"{first} {last[0]}." if last else first

    @property
    def actor_initials(self):
        return self.actor.initials if self.actor else "?"

    @property
    def target_name(self):
        if self.event:
            return self.event.title
        if self.organization:
            return self.organization.name
        return ""

    @property
    def target_url(self):
        if self.event:
            return self.event.get_absolute_url()
        if self.organization:
            return self.organization.get_absolute_url()
        return ""

    @property
    def university(self):
        if self.event and self.event.organization.university:
            return self.event.organization.university
        if self.organization:
            return self.organization.university
        return self.actor.university if self.actor else None

    @property
    def icon(self):
        return self.STYLES.get(self.verb, ("•", "slate"))[0]

    @property
    def tone(self):
        return self.STYLES.get(self.verb, ("•", "slate"))[1]

    @property
    def detail(self):
        """Trailing fragment, e.g. the amount paid or the stars given."""
        if self.verb == self.Verb.PAID and self.amount is not None:
            return f"USD {self.amount:,.2f}"
        if self.verb == self.Verb.REVIEWED and self.rating:
            return "★" * self.rating
        return ""

    def as_dict(self):
        return {
            "id": self.pk,
            "verb": self.verb,
            "phrase": self.get_verb_display(),
            "actor": self.actor_name,
            "initials": self.actor_initials,
            "target": self.target_name,
            "url": self.target_url,
            "university": str(self.university) if self.university else "",
            "detail": self.detail,
            "icon": self.icon,
            "tone": self.tone,
            "simulated": self.is_simulated,
            "ago": timesince_short(self.created_at),
        }


def timesince_short(when):
    """'just now', '4m', '2h' — short enough for a ticker row."""
    seconds = (timezone.now() - when).total_seconds()
    if seconds < 45:
        return "just now"
    if seconds < 3600:
        return f"{int(seconds // 60)}m"
    if seconds < 86400:
        return f"{int(seconds // 3600)}h"
    return f"{int(seconds // 86400)}d"


def record(verb, actor=None, event=None, organization=None, **extra):
    """Append one row to the stream.

    Deliberately forgiving: the feed is a nice-to-have, and a problem writing to
    it must never take down a registration or a payment.
    """
    try:
        return Activity.objects.create(
            verb=verb, actor=actor, event=event, organization=organization, **extra
        )
    except Exception:  # pragma: no cover - defensive
        import logging

        logging.getLogger(__name__).exception("Could not record activity %s", verb)
        return None
